import { BrokerProviderDefinition } from './brokerTypes';

export const BROKER_REGISTRY: BrokerProviderDefinition[] = [
  {
    providerId: 'zerodha',
    name: 'Zerodha Kite',
    tagline: 'India’s largest retail brokerage engine with ultra-fast Kite Connect APIs.',
    logoText: 'ZK',
    themeColor: '#FF5722',
    region: 'INDIA',
    authModel: 'API_KEY_SECRET',
    tokenLifecycle: {
      expiresDaily: true,
      expiryTimeLocal: '06:00 IST',
      maxLifetimeHours: 24,
      refreshStrategy: 'NONE_MANDATORY_REAUTH',
    },
    fields: [
      {
        id: 'clientId',
        label: 'Client ID (User ID)',
        placeholder: 'e.g. AB1234',
        type: 'text',
        required: true,
        isSecret: false,
        regexValidation: '^[A-Za-z]{2,3}[0-9]{4,6}$',
        validationErrorMessage: 'Client ID should be 6-8 alphanumeric characters (e.g., AB1234).',
        helperText: 'Your standard 6-character Zerodha Kite login username.',
      },
      {
        id: 'apiKey',
        label: 'Kite Connect API Key',
        placeholder: 'Enter 32-character API key...',
        type: 'text',
        required: true,
        isSecret: false,
        helperText: 'Generated from developer.zerodha.com after app subscription.',
      },
      {
        id: 'apiSecret',
        label: 'API Secret Vault Key',
        placeholder: '••••••••••••••••••••••••••••••••',
        type: 'password',
        required: true,
        isSecret: true,
        helperText: 'Encrypted at rest with AES-256 Cloud Security. Never shared.',
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'LIVE_QUOTES', 'WEBSOCKET_STREAM', 'HISTORICAL_DATA', 
      'MULTI_ACCOUNT', 'OPTIONS', 'FNO'
    ],
    documentation: {
      setupGuideUrl: 'https://kite.trade/docs/connect/v3/exceptions/',
      apiDocsUrl: 'https://kite.trade/docs/connect/v3/',
      officialPortalUrl: 'https://developers.zerodha.com/',
      troubleshootingUrl: 'https://kite.trade/forum/',
    },
  },
  {
    providerId: 'dhan',
    name: 'DhanHQ SuperAPI',
    tagline: 'Institutional lightning-fast direct market access with zero API charges.',
    logoText: 'DH',
    themeColor: '#00D09C',
    region: 'INDIA',
    authModel: 'DAILY_SESSION_TOKEN',
    tokenLifecycle: {
      expiresDaily: true,
      expiryTimeLocal: '23:59 IST',
      maxLifetimeHours: 24,
      refreshStrategy: 'NONE_MANDATORY_REAUTH',
    },
    fields: [
      {
        id: 'clientId',
        label: 'Dhan Client ID (Phone / Code)',
        placeholder: 'e.g. 1111734825 or 10-digit mobile',
        type: 'text',
        required: true,
        isSecret: false,
        regexValidation: '^[0-9]{8,12}$',
        validationErrorMessage: 'Enter your valid Dhan numeric user Client ID.',
        helperText: 'Your registered numeric Dhan Client Account ID.',
      },
      {
        id: 'accessToken',
        label: 'Daily SuperAPI Access Token',
        placeholder: 'Paste your daily access token here...',
        type: 'password',
        required: true,
        isSecret: true,
        helperText: 'Generate in 1-click from Dhan web web.dhan.co -> My Profile -> DhanHQ API.',
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'LIVE_QUOTES', 'WEBSOCKET_STREAM', 'HISTORICAL_DATA', 
      'MULTI_ACCOUNT', 'OPTIONS', 'FNO'
    ],
    documentation: {
      setupGuideUrl: 'https://dhanhq.co/docs/v2/',
      apiDocsUrl: 'https://dhanhq.co/docs/v2/',
      officialPortalUrl: 'https://web.dhan.co/',
      troubleshootingUrl: 'https://community.dhan.co/',
    },
  },
  {
    providerId: 'angelone',
    name: 'Angel One SmartAPI',
    tagline: 'Robust multi-asset API integration with native automated TOTP challenges.',
    logoText: 'AO',
    themeColor: '#3B82F6',
    region: 'INDIA',
    authModel: 'CLIENT_ID_SECRET_TOTP',
    tokenLifecycle: {
      expiresDaily: true,
      expiryTimeLocal: '06:00 IST',
      maxLifetimeHours: 24,
      refreshStrategy: 'NONE_MANDATORY_REAUTH',
    },
    fields: [
      {
        id: 'clientId',
        label: 'Angel Client Code',
        placeholder: 'e.g. A123456 or S987654',
        type: 'text',
        required: true,
        isSecret: false,
        helperText: 'Your Angel One login User ID (shown on the SmartAPI dashboard).',
      },
      {
        id: 'apiKey',
        label: 'SmartAPI App Key',
        placeholder: 'Enter your app API key...',
        type: 'text',
        required: true,
        isSecret: false,
        helperText: 'Get it from smartapi.angelbroking.com → My Apps → Create App.',
      },
      {
        id: 'mpin',
        label: 'Trading MPIN',
        placeholder: '••••',
        type: 'password',
        required: true,
        isSecret: true,
        regexValidation: '^[0-9]{4,8}$',
        validationErrorMessage: 'Must be a 4–8 digit numeric PIN.',
        helperText: 'The numeric PIN you use to log into the Angel One trading terminal.',
      },
      {
        id: 'totpSecret',
        label: 'TOTP Secret (Base32 Key)',
        placeholder: 'e.g. JBSWY3DPEHPK3PXP...',
        type: 'password',
        required: true,
        isSecret: true,
        helperText: 'The Base32 key from smartapi.angelbroking.com → Enable TOTP. NOT the 6-digit OTP — the setup key. Stored securely for automatic daily re-auth.',
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'HISTORICAL_DATA', 'MULTI_ACCOUNT', 'OPTIONS', 'FNO'
    ],
    documentation: {
      setupGuideUrl: 'https://smartapi.angelbroking.com/docs',
      apiDocsUrl: 'https://smartapi.angelbroking.com/docs/Orders',
      officialPortalUrl: 'https://smartapi.angelbroking.com/',
      troubleshootingUrl: 'https://smartapi.angelbroking.com/topic',
    },
  },
  {
    providerId: 'upstox',
    name: 'Upstox Developer V2',
    tagline: 'High-speed institutional OAuth 2.0 streaming pipeline for derivatives.',
    logoText: 'UP',
    themeColor: '#7C3AED',
    region: 'INDIA',
    authModel: 'OAUTH2',
    tokenLifecycle: {
      expiresDaily: false,
      maxLifetimeHours: 720,
      refreshStrategy: 'OAUTH_SILENT_GRANT',
    },
    fields: [
      {
        id: 'apiKey',
        label: 'Upstox App API Key',
        placeholder: 'Enter Upstox Client API Key...',
        type: 'text',
        required: true,
        isSecret: false,
        helperText: 'Obtain from developer.upstox.com portal.',
      },
      {
        id: 'apiSecret',
        label: 'OAuth Client Secret',
        placeholder: '••••••••••••••••••••••••••••••••',
        type: 'password',
        required: true,
        isSecret: true,
        helperText: 'Used for automatic background PKCE OAuth token refresh exchanges.',
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'LIVE_QUOTES', 'WEBSOCKET_STREAM', 'HISTORICAL_DATA', 
      'MULTI_ACCOUNT', 'OPTIONS', 'FNO', 'MUTUAL_FUNDS'
    ],
    documentation: {
      setupGuideUrl: 'https://upstox.com/developer/api-documentation',
      apiDocsUrl: 'https://upstox.com/developer/api-documentation',
      officialPortalUrl: 'https://developer.upstox.com/',
    },
  },
  {
    providerId: 'groww',
    name: 'Groww Alpha API',
    tagline: 'Modern investing terminal integration with automated ledger sync.',
    logoText: 'GR',
    themeColor: '#00D09C',
    region: 'INDIA',
    authModel: 'API_KEY_SECRET',
    tokenLifecycle: {
      expiresDaily: true,
      maxLifetimeHours: 24,
      refreshStrategy: 'NONE_MANDATORY_REAUTH',
    },
    fields: [
      {
        id: 'clientId',
        label: 'Groww Customer Id / Email',
        placeholder: 'trader@domain.com',
        type: 'text',
        required: true,
        isSecret: false,
      },
      {
        id: 'apiKey',
        label: 'Alpha API Key',
        placeholder: 'Paste Groww Alpha API key...',
        type: 'password',
        required: true,
        isSecret: true,
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'PNL', 'HISTORICAL_DATA', 'MUTUAL_FUNDS'
    ],
    documentation: {
      setupGuideUrl: 'https://groww.in/',
      apiDocsUrl: 'https://groww.in/',
      officialPortalUrl: 'https://groww.in/',
    },
  },
  {
    providerId: '5paisa',
    name: '5paisa Developer API',
    tagline: 'Discount brokerage automated algorithm integration suite.',
    logoText: '5P',
    themeColor: '#EF4444',
    region: 'INDIA',
    authModel: 'API_KEY_SECRET',
    tokenLifecycle: {
      expiresDaily: true,
      maxLifetimeHours: 24,
      refreshStrategy: 'NONE_MANDATORY_REAUTH',
    },
    fields: [
      {
        id: 'clientId',
        label: 'Client Login Code',
        placeholder: 'e.g. 52345678',
        type: 'text',
        required: true,
        isSecret: false,
      },
      {
        id: 'apiKey',
        label: 'User Key (App Key)',
        placeholder: 'Enter 5paisa App Key...',
        type: 'text',
        required: true,
        isSecret: false,
      },
      {
        id: 'apiSecret',
        label: 'Encryption Secret Key',
        placeholder: '••••••••••••••••••••••••••••••••',
        type: 'password',
        required: true,
        isSecret: true,
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'HISTORICAL_DATA', 'OPTIONS', 'FNO'
    ],
    documentation: {
      setupGuideUrl: 'https://www.5paisa.com/developerapi',
      apiDocsUrl: 'https://www.5paisa.com/developerapi',
      officialPortalUrl: 'https://www.5paisa.com/',
    },
  },
  {
    providerId: 'bullforce',
    name: 'BullForce Quant Portal',
    tagline: 'Global cryptocurrency and international liquidity institutional execution connector.',
    logoText: 'BF',
    themeColor: '#F59E0B',
    region: 'GLOBAL',
    authModel: 'JWT',
    tokenLifecycle: {
      expiresDaily: false,
      maxLifetimeHours: 720,
      refreshStrategy: 'REFRESH_TOKEN_AUTOMATIC',
    },
    fields: [
      {
        id: 'clientId',
        label: 'Account Unique Tag / Alias',
        placeholder: 'e.g. Master-Fund-1',
        type: 'text',
        required: true,
        isSecret: false,
      },
      {
        id: 'accessToken',
        label: 'Institutional JWT Bearer Key',
        placeholder: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...',
        type: 'password',
        required: true,
        isSecret: true,
        helperText: 'Persistent quantitative bearer signature with automated rolling background lease.',
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'LIVE_QUOTES', 'WEBSOCKET_STREAM', 'HISTORICAL_DATA', 
      'MULTI_ACCOUNT'
    ],
    documentation: {
      setupGuideUrl: 'https://RiskRules.in/docs/bullforce',
      apiDocsUrl: 'https://RiskRules.in/docs/bullforce/api',
      officialPortalUrl: 'https://RiskRules.in/',
    },
  },
  {
    providerId: 'delta_exchange',
    name: 'Delta Exchange',
    tagline: 'High-performance crypto options, futures, and spot derivatives exchange API.',
    logoText: 'DE',
    themeColor: '#10B981',
    region: 'GLOBAL',
    authModel: 'API_KEY_SECRET',
    tokenLifecycle: {
      expiresDaily: false,
      maxLifetimeHours: 8760,
      refreshStrategy: 'NONE_MANDATORY_REAUTH',
    },
    fields: [
      {
        id: 'apiKey',
        label: 'Delta API Key',
        placeholder: 'Enter 32+ character API key...',
        type: 'text',
        required: true,
        isSecret: false,
        helperText: 'Generated from Delta Exchange -> Profile / Settings -> API Keys.',
      },
      {
        id: 'apiSecret',
        label: 'Delta API Secret Key',
        placeholder: '••••••••••••••••••••••••••••••••',
        type: 'password',
        required: true,
        isSecret: true,
        helperText: 'Secret key provided when creating the Delta Exchange API key.',
      },
    ],
    capabilities: [
      'AUTO_SYNC', 'PORTFOLIO', 'HOLDINGS', 'POSITIONS', 'ORDERS', 
      'MARGIN', 'PNL', 'LIVE_QUOTES', 'WEBSOCKET_STREAM', 'HISTORICAL_DATA', 
      'MULTI_ACCOUNT', 'OPTIONS', 'FNO', 'CRYPTO'
    ],
    documentation: {
      setupGuideUrl: 'https://docs.delta.exchange/#authentication',
      apiDocsUrl: 'https://docs.delta.exchange/',
      officialPortalUrl: 'https://www.delta.exchange/',
    },
  },
];

export function getBrokerProvider(providerId: string): BrokerProviderDefinition | undefined {
  return BROKER_REGISTRY.find(b => b.providerId === providerId);
}
