import React from 'react';
import { Scale } from 'lucide-react';
import { motion } from 'framer-motion';

export default function Terms() {
  return (
    <div className="min-h-screen bg-canvas pt-32 pb-24 selection:bg-primary/20">
      <div className="max-w-4xl mx-auto px-6">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-semibold mb-6">
            <Scale className="w-4 h-4" />
            <span>Legal Agreement</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-bold text-primary tracking-tight mb-6 font-display">
            Terms of Service
          </h1>
          <p className="text-xl text-secondary max-w-2xl leading-relaxed">
            By accessing or using TradeVault, you agree to be bound by these terms. 
            Designed for professional market participants.
          </p>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="prose prose-invert prose-lg max-w-none prose-headings:font-display prose-headings:font-bold prose-headings:text-primary prose-p:text-secondary prose-a:text-iris prose-a:no-underline hover:prose-a:underline"
        >
          <p className="text-tertiary text-sm">Last Updated: October 1, 2026</p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            These Terms of Service ("Terms") govern your use of the TradeVault platform, software, and associated services (collectively, the "Service"). By creating an account or using the Service, you signify your acceptance of these Terms. If you do not agree to these Terms, do not use the Service.
          </p>

          <h2>2. Description of Service</h2>
          <p>
            TradeVault is an analytics and behavioral journaling platform for traders. The Service includes features such as trade logging, performance analytics, AI-driven behavioral insights, and market data visualization. <strong>TradeVault is not a broker-dealer or investment advisor.</strong>
          </p>

          <h2>3. No Financial Advice</h2>
          <p>
            All information, AI insights, and market data provided through the Service are for educational and informational purposes only. None of the content generated by the Service constitutes financial, investment, or trading advice. You are solely responsible for your trading decisions and any financial losses incurred.
          </p>

          <h2>4. User Accounts &amp; Security</h2>
          <p>
            You are responsible for maintaining the confidentiality of your account credentials. You agree to notify TradeVault immediately of any unauthorized use of your account. TradeVault will not be liable for any losses caused by unauthorized access to your account.
          </p>

          <h2>5. Subscription &amp; Billing</h2>
          <p>
            Certain features of the Service require a paid subscription. By selecting a subscription tier, you agree to pay all applicable fees. Subscriptions automatically renew unless canceled prior to the renewal date. All fees are non-refundable unless otherwise required by law.
          </p>

          <h2>6. API Usage &amp; Broker Sync</h2>
          <p>
            When utilizing the Broker Sync features, you authorize TradeVault to access your third-party broker accounts on a read-only basis. You agree to comply with all terms and conditions of your respective brokers. TradeVault is not responsible for API outages, sync delays, or discrepancies in data provided by third-party APIs.
          </p>

          <h2>7. Acceptable Use Policy</h2>
          <p>
            You agree not to misuse the Service. Misuse includes, but is not limited to:
          </p>
          <ul>
            <li>Attempting to reverse-engineer, decompile, or hack the platform.</li>
            <li>Using automated scripts or bots to scrape data from the platform.</li>
            <li>Sharing a single account subscription across multiple unassociated users (institutional plans excluded).</li>
          </ul>

          <h2>8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, TradeVault and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, or goodwill, arising out of your access to or use of the Service.
          </p>

          <h2>9. Modifications to the Service</h2>
          <p>
            TradeVault reserves the right to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice. We shall not be liable to you or any third party for any modification, price change, suspension, or discontinuance of the Service.
          </p>

          <h2>10. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which TradeVault Inc. is registered, without regard to its conflict of law provisions.
          </p>

          <h2>Contact</h2>
          <p>
            For legal inquiries, please contact our legal department at <strong>legal@tradevault.com</strong>.
          </p>
        </motion.div>
      </div>
    </div>
  );
}
