/**
 * Disposable & Temporary Email Detection Module
 *
 * Validates email structure and rejects temporary, disposable, burner,
 * and throwaway mailbox providers.
 */

// Strict RFC 5322 compatible email regex
const EMAIL_REGEX = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/;

// Set of known disposable / throwaway email provider domains (lowercased)
const DISPOSABLE_DOMAINS = new Set<string>([
  '0815.ru',
  '10minemail.com',
  '10minutemail.be',
  '10minutemail.cf',
  '10minutemail.co.uk',
  '10minutemail.co.za',
  '10minutemail.com',
  '10minutemail.de',
  '10minutemail.ga',
  '10minutemail.gq',
  '10minutemail.info',
  '10minutemail.ml',
  '10minutemail.net',
  '10minutemail.nl',
  '10minutemail.org',
  '10minutemail.pl',
  '10minutemailbox.com',
  '10minutemailpro.com',
  '20minutemail.com',
  '20minutemail.it',
  '2prong.com',
  '33mail.com',
  'abcvg.com',
  'amilelegit.com',
  'anonaddy.me',
  'anonbox.net',
  'anonymbox.com',
  'antichef.com',
  'antichef.net',
  'antispam.de',
  'armyspy.com',
  'baxomale.ht.cx',
  'beefmilk.com',
  'bigstring.com',
  'binkmail.com',
  'bio-muesli.net',
  'bitmessage.ch',
  'blackhole.io',
  'bobmail.info',
  'brefmail.com',
  'bspamfree.org',
  'bupkis.org',
  'burnermail.io',
  'cachedot.net',
  'cashette.com',
  'centermail.com',
  'centermail.net',
  'chacuo.net',
  'chogmail.com',
  'choicemail1.com',
  'clrmail.com',
  'cobrabit.com',
  'comic.com',
  'cool.fr.nf',
  'correo.blogos.net',
  'cosmorph.com',
  'courriel.fr.nf',
  'courrieltemporaire.com',
  'crapmail.org',
  'crazymailing.com',
  'cuvox.de',
  'dandikmail.com',
  'dayrep.com',
  'deadaddress.com',
  'deadfake.cf',
  'deadfake.ga',
  'deadfake.gq',
  'deadfake.ml',
  'deadfake.tk',
  'delikmail.com',
  'despam.it',
  'despammed.com',
  'devnullmail.com',
  'dfgh.net',
  'digitalsanctuary.com',
  'discard.email',
  'discard.im',
  'discardmail.com',
  'discardmail.de',
  'disposable.com',
  'disposable.email',
  'disposableinbox.com',
  'disposablemail.com',
  'dispostable.com',
  'dodgeit.com',
  'dodgit.com',
  'dontreg.com',
  'dontsendmespam.de',
  'drdrb.com',
  'drdrb.net',
  'dropmail.me',
  'duetmail.com',
  'dump-email.info',
  'dumpemail.de',
  'dumpmail.de',
  'dumpyemail.com',
  'e4ward.com',
  'easytrashmail.com',
  'einrot.com',
  'email-fake.com',
  'email-free.org',
  'email-generator.org',
  'email-jetable.fr',
  'email-temp.com',
  'email60.com',
  'emailage.com',
  'emaildienst.de',
  'emailgo.de',
  'emailias.com',
  'emailigo.de',
  'emailinfive.com',
  'emailmiser.com',
  'emailondeck.com',
  'emailproxsy.com',
  'emailresender.com',
  'emailsensei.com',
  'emailservice.biz',
  'emailshelf.com',
  'emailslots.com',
  'emailspao.com',
  'emailspoon.com',
  'emailstogo.com',
  'emailszone.com',
  'emailtemporaneo.com',
  'emailtemporaneo.net',
  'emailtemporar.ro',
  'emailtemporario.com.br',
  'emailthe.net',
  'emailto.de',
  'emailure.net',
  'emailvalid.com',
  'emailx.at.tc',
  'emailx.biz',
  'emailz.org',
  'emeil.in',
  'emeil.ir',
  'ephemail.net',
  'epicemail.net',
  'evade.me.uk',
  'everymail.biz',
  'evopo.com',
  'exp-mail.com',
  'expires-30-days.org',
  'expires-today.org',
  'extramail.biz',
  'eyepaste.com',
  'ezmail.at.tc',
  'ezmail.biz',
  'fake-box.com',
  'fake-email.pp.ua',
  'fake-mail.biz',
  'fake-mail.org',
  'fakeemail.net',
  'fakeinbox.com',
  'fakemail.io',
  'fakemail.net',
  'fakemailgenerator.com',
  'fakermail.com',
  'fast-email.org',
  'fast-mail.org',
  'fastacura.com',
  'fastchevy.com',
  'fastchrysler.com',
  'fastdodge.com',
  'fastford.com',
  'fasthonda.com',
  'fastmazda.com',
  'fastmitsubishi.com',
  'fastnissan.com',
  'fastsubaru.com',
  'fastsuzuki.com',
  'fasttoyota.com',
  'fastyamaha.com',
  'filzmail.com',
  'fivemail.de',
  'fixmail.at.tc',
  'fleckens.hu',
  'flemail.ru',
  'fly-mailer.com',
  'flyspam.com',
  'footard.com',
  'forward.cat',
  'free-email.org',
  'freemail.ms',
  'freemailnospam.free.fr',
  'freemailstore.com',
  'freundin.ru',
  'front14.org',
  'fudgegot.info',
  'fux0ringduh.com',
  'garbage-mail.com',
  'garbagemail.org',
  'gemmail.net',
  'generator.email',
  'get-mail.at.tc',
  'get-mail.biz',
  'get1mail.com',
  'get2mail.fr',
  'getairmail.com',
  'getnada.com',
  'getonemail.biz',
  'getonemail.com',
  'getonemail.net',
  'ghostmailer.net',
  'giantmail.de',
  'gimme-food.com',
  'ginormousmail.com',
  'girlymail.com',
  'gishpuppy.com',
  'glammail.net',
  'globalmail.biz',
  'gluemail.biz',
  'go-email.org',
  'go-mailer.com',
  'go-spam.com',
  'gocoolmail.com',
  'gokeymail.com',
  'golfingmail.com',
  'goroundmail.com',
  'gotspam.org',
  'grapemail.net',
  'greensloth.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.block',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.info',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'haltospam.com',
  'harakirimail.com',
  'hartbot.de',
  'hasmail.biz',
  'hatespam.org',
  'hazelnutmail.com',
  'headstrongmail.com',
  'heapsmail.com',
  'herp.in',
  'hide-mail.com',
  'hidemail.biz',
  'hidemail.de',
  'hidemail.info',
  'hidemail.net',
  'hidemail.org',
  'hidemailbox.com',
  'highdefinitionmail.com',
  'hintmail.com',
  'hitmail.biz',
  'hizmail.com',
  'hmamail.com',
  'hogmail.biz',
  'homemail.biz',
  'hopmail.biz',
  'hot-mail.at.tc',
  'hot-mailer.com',
  'hot-spam.com',
  'hotemails.biz',
  'hotletters.biz',
  'hotletters.net',
  'hotletterz.biz',
  'hotletterz.net',
  'hotm.at.tc',
  'hotm.biz',
  'hotmailer.at.tc',
  'hotpop.com',
  'hovermail.biz',
  'hoxmail.com',
  'html-email.org',
  'hugeinbox.com',
  'hugemail.biz',
  'humn.ws',
  'hypermail.biz',
  'hyperspam.com',
  'i-mail.at.tc',
  'i-mailer.com',
  'i-spam.com',
  'i2pmail.org',
  'iban.is',
  'ibonweb.com',
  'icemail.biz',
  'ich-will-keinen-spam.de',
  'ich-will-keins.de',
  'ich-will-net.de',
  'ich-will.net',
  'id-email.org',
  'id-mailer.com',
  'id-spam.com',
  'idmail.biz',
  'idmailer.com',
  'idspammers.com',
  'ignorelist.com',
  'ihateyouremail.com',
  'iknowwhatyoudid.net',
  'imgof.com',
  'imgv.de',
  'imnobody.net',
  'in-mail.at.tc',
  'in-mailer.com',
  'in-spam.com',
  'inbox.si',
  'inbox2.biz',
  'inboxalias.com',
  'inboxclean.com',
  'inboxclean.org',
  'inboxdesign.me',
  'inboxinc.com',
  'inboxkitten.com',
  'inboxproxy.com',
  'inboxstore.me',
  'incognitomail.com',
  'incognitomail.net',
  'incognitomail.org',
  'inorbitmail.com',
  'insorg-mail.info',
  'instant-email.biz',
  'instant-email.info',
  'instant-email.net',
  'instant-email.org',
  'instant-mail.biz',
  'instant-mail.info',
  'instant-mail.net',
  'instant-mail.org',
  'instant-mailer.com',
  'instant-spam.com',
  'instantaddress.biz',
  'instantaddress.net',
  'instantaddress.org',
  'instantemail.at.tc',
  'instantemail.biz',
  'instantemailaddress.com',
  'instantmail.at.tc',
  'instantmail.biz',
  'instantmail.org',
  'instantmailer.biz',
  'instantmailer.com',
  'instantmailer.net',
  'instantmailer.org',
  'instantreceive.com',
  'intermail.biz',
  'internet-email.org',
  'internet-mailer.com',
  'internet-spam.com',
  'internetemails.net',
  'internetletters.biz',
  'internetletters.net',
  'intomail.biz',
  'intomail.com',
  'intomail.net',
  'intomail.org',
  'ioviso.biz',
  'ioviso.com',
  'ip6.li',
  'ipoo.org',
  'iprimus.biz',
  'itemp.email',
  'itempmail.com',
  'itsme.at.tc',
  'itsspruce.com',
  'itsvortex.com',
  'j-mail.at.tc',
  'jetable.com',
  'jetable.fr.nf',
  'jetable.net',
  'jetable.org',
  'jetable.pp.ru',
  'jetables.biz',
  'jourrapide.com',
  'junk-mail.at.tc',
  'junk1e.com',
  'junkemail.at.tc',
  'junkmail.at.tc',
  'junkmail.biz',
  'junkmail.net',
  'junkmail.org',
  'junkmail0.com',
  'junkmail1.com',
  'junkmail2.com',
  'junkmailer.biz',
  'junkmailfilter.com',
  'just-email.org',
  'justemail.at.tc',
  'justemail.biz',
  'justmail.at.tc',
  'justmail.biz',
  'justmailer.com',
  'kaffeeschluerfer.com',
  'kasmail.com',
  'kasper.in',
  'keepmymail.com',
  'keemail.me',
  'kein-bock-auf-spam.de',
  'keine-werbung.de',
  'keinen-bock-auf-spam.de',
  'keinen-spam.de',
  'keinspam.biz',
  'keinspam.de',
  'keinspam.info',
  'keinspam.net',
  'keinspam.org',
  'kick-spam.com',
  'kill-the-spam.com',
  'killmail.biz',
  'killmail.net',
  'klzlk.com',
  'koszmail.pl',
  'kurzepost.de',
  'labetterave.com',
  'last-minute-mail.com',
  'last-minute-mail.de',
  'lastminutemail.biz',
  'lastminutemail.com',
  'lastminutemail.de',
  'lastminutemail.net',
  'lastminutemail.org',
  'lawlita.com',
  'lazyinbox.com',
  'lead-seller.com',
  'lellno.com',
  'letthemeatspam.com',
  'letterbox.biz',
  'lifebyfood.com',
  'link2mail.net',
  'liteemail.biz',
  'litemail.at.tc',
  'litemail.biz',
  'litemailer.com',
  'littleinbox.com',
  'liveemail.biz',
  'livemail.at.tc',
  'livemailer.com',
  'lolfreak.net',
  'lolito.com',
  'lookugly.com',
  'loves-it.com',
  'lovesit.biz',
  'loveyourspam.com',
  'lowcostemail.com',
  'lowcostmail.com',
  'lukin.ch',
  'luna-mail.com',
  'lutak.com',
  'm2x.eu',
  'mac-address.org',
  'magicemail.biz',
  'magicmail.at.tc',
  'magicmailer.com',
  'mail-drop.net',
  'mail-easy.com',
  'mail-free.biz',
  'mail-ghost.com',
  'mail-owl.com',
  'mail-owl.de',
  'mail-temp.com',
  'mail-temp.net',
  'mail-temporaire.com',
  'mail-temporaire.fr',
  'mail-to.biz',
  'mail-trash.com',
  'mail.by',
  'mail.ht.cx',
  'mail.ru.ms',
  'mail2rss.org',
  'mail333.com',
  'mail4-you.com',
  'mail4free.biz',
  'mailambit.com',
  'mailas.com',
  'mailay.com',
  'mailbare.com',
  'mailblocks.com',
  'mailcan.com',
  'mailcatch.com',
  'maildrop.cc',
  'mailexpire.com',
  'mailforspam.com',
  'mailhazard.com',
  'mailimate.com',
  'mailin8r.com',
  'mailinate.com',
  'mailinator.com',
  'mailinator.net',
  'mailinator.org',
  'mailinator2.com',
  'mailismagic.com',
  'mailmetrash.com',
  'mailmoat.com',
  'mailnesia.com',
  'mailnull.com',
  'mailsac.com',
  'mailshell.com',
  'mailtothis.com',
  'meltmail.com',
  'mintemail.com',
  'mycleaninbox.com',
  'mytemp.email',
  'mytempemail.com',
  'nada.email',
  'nada.ltd',
  'nobulk.com',
  'noclickemail.com',
  'nomail.xl.cx',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'notsharingmy.info',
  'nowmymail.com',
  'objectmail.com',
  'obobbo.com',
  'oneoffmail.com',
  'pookmail.com',
  'privacy.net',
  'proxymail.eu',
  'rcpt.at',
  'recode.me',
  'safetymail.info',
  'sandelf.de',
  'sharklasers.com',
  'shieldemail.com',
  'shortmail.net',
  'sogetthis.com',
  'soodonims.com',
  'spambob.com',
  'spambob.net',
  'spambob.org',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.us',
  'spamcan.org',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamday.com',
  'spamex.com',
  'spamfree24.org',
  'spamgourmet.com',
  'spamhole.com',
  'spaminator.de',
  'spammotel.com',
  'spamspot.com',
  'spamtrap.ro',
  'spamyourself.com',
  'temp-mail.io',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempemail.co',
  'tempemail.net',
  'tempinbox.com',
  'tempm.com',
  'temporaryemail.net',
  'temporaryinbox.com',
  'tempmail.com',
  'tempmail.net',
  'tempmail.plus',
  'throwawaymail.com',
  'tinemail.com',
  'trash-mail.at',
  'trash-mail.com',
  'trash-mail.de',
  'trash-me.com',
  'trashcanmail.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.io',
  'trashmail.net',
  'trashmail.org',
  'trashmailer.com',
  'trashymail.com',
  'trillianpro.com',
  'uggsrock.com',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'whyspam.me',
  'willhackforfood.biz',
  'wuzup.net',
  'wuzupmail.net',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'youpymail.com',
  'zillamail.com',
  'zippymail.info',
  'zoemail.org'
]);

/**
 * Validates whether an email format conforms to standard syntax rules.
 */
export function isValidEmailFormat(email: string): boolean {
  if (!email || typeof email !== 'string') return false;
  const trimmed = email.trim();
  if (trimmed.length < 5 || trimmed.length > 254) return false;
  
  // Check basic RFC format
  if (!EMAIL_REGEX.test(trimmed)) return false;

  const parts = trimmed.split('@');
  if (parts.length !== 2) return false;
  
  const [localPart, domain] = parts;
  if (localPart.length === 0 || localPart.length > 64) return false;
  if (domain.length === 0 || domain.length > 255) return false;

  // Domain must have at least one dot and valid top-level domain
  const domainParts = domain.split('.');
  if (domainParts.length < 2) return false;
  const tld = domainParts[domainParts.length - 1];
  if (tld.length < 2 || !/^[a-zA-Z]{2,}$/.test(tld)) return false;

  return true;
}

/**
 * Checks whether an email domain belongs to known disposable/temporary mailbox services.
 */
export function isDisposableEmail(email: string): boolean {
  if (!email || typeof email !== 'string') return false;
  const trimmed = email.trim().toLowerCase();
  const atIndex = trimmed.lastIndexOf('@');
  if (atIndex === -1) return false;

  const domain = trimmed.slice(atIndex + 1).toLowerCase();
  if (!domain) return false;

  // Direct domain match
  if (DISPOSABLE_DOMAINS.has(domain)) {
    return true;
  }

  // Check parent domains / subdomains (e.g., sub.mailinator.com, user.yopmail.fr)
  const parts = domain.split('.');
  for (let i = 0; i < parts.length - 1; i++) {
    const subDomain = parts.slice(i).join('.');
    if (DISPOSABLE_DOMAINS.has(subDomain)) {
      return true;
    }
  }

  // Heuristic keywords pattern for throwaway email domains
  const suspiciousKeywords = [
    'mailinator',
    'guerrillamail',
    'tempmail',
    'temp-mail',
    'throwawaymail',
    '10minutemail',
    'dispostable',
    'trashmail',
    'fakemail',
    'fakeinbox',
    'yopmail',
    'sharklasers',
    'getnada',
    'burnermail',
    'emailondeck',
    'mohmal',
    'crazymailing',
  ];

  for (const keyword of suspiciousKeywords) {
    if (domain.startsWith(keyword) || domain.includes(`.${keyword}.`) || domain.includes(`-${keyword}`)) {
      return true;
    }
  }

  return false;
}

/**
 * Full email validation: format check + disposable check.
 * Returns null if valid, or an error message string if invalid.
 */
export function validateEmail(email: string): string | null {
  if (!email || !email.trim()) {
    return 'Email address is required.';
  }
  if (!isValidEmailFormat(email)) {
    return 'Please enter a valid email address.';
  }
  if (isDisposableEmail(email)) {
    return 'Temporary or disposable email addresses are not permitted. Please use a permanent email address.';
  }
  return null;
}
