export const DISCIPLINE_VERSION = 1;

export const SIGNAL_WEIGHTS = {
  ENTRY_TIMING: {
    BEFORE_930: -0.5,
    AFTER_1500: -0.5,
    NORMAL: 0,
  },
  HOLD_TIME: {
    DERIVATIVE_TOO_SHORT_MINS: 5,
    DERIVATIVE_TOO_SHORT_PENALTY: -0.5,
    DERIVATIVE_GOOD_HOLD_MINS: 60,
    DERIVATIVE_GOOD_HOLD_BONUS: 0.5,
    EQ_TOO_SHORT_MINS: 1,
    EQ_TOO_SHORT_PENALTY: -0.5,
    EQ_GOOD_HOLD_MINS: 30,
    EQ_GOOD_HOLD_BONUS: 0.5,
  },
  SIZING: {
    OVERSIZED_RATIO: 1.5,
    OVERSIZED_PENALTY: -0.5,
    UNDERSIZED_RATIO: 0.5,
    UNDERSIZED_PENALTY: -0.2,
    CONSISTENT_MIN_RATIO: 0.9,
    CONSISTENT_MAX_RATIO: 1.1,
    CONSISTENT_BONUS: 0.5,
  },
  REVENGE: {
    MAX_GAP_MINS: 10,
    PENALTY_PER_INSTANCE: -0.5,
  },
  PERSONAL_RULES: {
    WINDOW_VIOLATION: -0.5,
    MAX_TRADES_VIOLATION: -0.5,
    MAX_DAILY_LOSS_VIOLATION: -1.0,
    MAX_PER_TRADE_LOSS_VIOLATION: -0.5,
    INSTRUMENT_VIOLATION: -0.5,
    MARKET_VIOLATION: -0.5,
  }
};
